#!/usr/bin/env bash
# Regenerate .github/dependabot.yml with one gomod entry per module directory.
# Run from repo root: tools/gen-dependabot.sh
set -euo pipefail

OUT=.github/dependabot.yml

# Collect + sort module directories, stripped of leading './'.
mapfile -t MODS < <(find . -name 'go.mod' -not -path './.workingdir*/*' -exec dirname {} \; | sed 's|^\./||' | sort)

{
  cat <<'EOF'
# Auto-generated by tools/gen-dependabot.sh. Do not hand-edit; re-run the
# script when a module is added or removed.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

EOF
  for mod in "${MODS[@]}"; do
    if [ "$mod" = "." ]; then
      dir="/"
    else
      dir="/$mod"
    fi
    cat <<EOF
  - package-ecosystem: "gomod"
    directory: "${dir}"
    schedule:
      interval: "weekly"
    groups:
      stdlib-compat:
        patterns: ["*"]
    open-pull-requests-limit: 5
EOF
  done
} > "$OUT"

echo "wrote $OUT with ${#MODS[@]} gomod entries"
